# 训练相关参数
batch_size: 16               # 批量个数
ckpt_dir: './checkpoints'
checkpoints: ''
logs_dir: './logs'          # 日志路径
logs_freq: 20               # 日志频率
print_freq: 1              # 打印频率
ckpt_freq: 20                # 权重频率
num_workers: 4              # 数据加载线程数
is_shuffle: True
start_epoch: 0
end_epoch: 140
resume: false
optimizer_type: 'adam'
lr: 0.001
lr_type: 'multi_step'
lr_step: [90, 120]
weight_decay: 0.0001        # 权重衰减系数
gamma1: 0.99
gamma2: 0.0
momentum: 0.9               # 动量值/衰减值

# 损失相关参数
use_target_weight: False

# 网络相关参数
input_size: [256, 192]
heatmap_size: [64, 48]
num_keypoints: 6
pretrained: './weights/resnet50-19c8e357.pth'

train_image: 'F:\\img'
train_label: 'F:\\anno'

test_image: 'F:\\SuperB_Training_3W_20200928'
test_label: 'F:\\SuperB_Training_3W_20200928\\Graviti_SuperB_Training_3W_20200928\\vdet'

hflip: 0.5
rotate_factor: 40
scale_factor: 0.3

# 验证相关参数
val_batch_size: 16
val_model_ckpt: ''

# 调试相关参数
debug: True
save_batch_images_gt: True
save_batch_images_pred: True
save_heatmaps_gt: True
save_heatmaps_pred: True